# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Adam\Documents\untitled.ui'
#
# Created: Sat Apr 25 17:27:38 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(712, 342)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 711, 341))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 451, 291))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.DataLabel = QtGui.QLabel(self.groupBox)
        self.DataLabel.setGeometry(QtCore.QRect(10, 110, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.DataLabel.setFont(font)
        self.DataLabel.setObjectName(_fromUtf8("DataLabel"))
        self.DataText = QtGui.QLineEdit(self.groupBox)
        self.DataText.setGeometry(QtCore.QRect(10, 140, 251, 20))
        self.DataText.setObjectName(_fromUtf8("DataText"))
        self.ResultText = QtGui.QLineEdit(self.groupBox)
        self.ResultText.setGeometry(QtCore.QRect(10, 260, 251, 20))
        self.ResultText.setObjectName(_fromUtf8("ResultText"))
        self.ResultLabel = QtGui.QLabel(self.groupBox)
        self.ResultLabel.setGeometry(QtCore.QRect(10, 230, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ResultLabel.setFont(font)
        self.ResultLabel.setObjectName(_fromUtf8("ResultLabel"))
        self.KeyLabel = QtGui.QLabel(self.groupBox)
        self.KeyLabel.setGeometry(QtCore.QRect(10, 170, 85, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KeyLabel.setFont(font)
        self.KeyLabel.setObjectName(_fromUtf8("KeyLabel"))
        self.KeyText = QtGui.QLineEdit(self.groupBox)
        self.KeyText.setGeometry(QtCore.QRect(10, 200, 251, 20))
        self.KeyText.setObjectName(_fromUtf8("KeyText"))
        self.KCVTEXT = QtGui.QLineEdit(self.groupBox)
        self.KCVTEXT.setGeometry(QtCore.QRect(280, 200, 113, 20))
        self.KCVTEXT.setObjectName(_fromUtf8("KCVTEXT"))
        self.KCVLabel = QtGui.QLabel(self.groupBox)
        self.KCVLabel.setGeometry(QtCore.QRect(320, 170, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.KCVLabel.setFont(font)
        self.KCVLabel.setObjectName(_fromUtf8("KCVLabel"))
        self.KCVButton = QtGui.QPushButton(self.groupBox)
        self.KCVButton.setGeometry(QtCore.QRect(290, 220, 101, 23))
        self.KCVButton.setObjectName(_fromUtf8("KCVButton"))
        self.lineEdit_6 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 70, 251, 20))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.VectorLabel = QtGui.QLabel(self.groupBox)
        self.VectorLabel.setGeometry(QtCore.QRect(10, 40, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.VectorLabel.setFont(font)
        self.VectorLabel.setObjectName(_fromUtf8("VectorLabel"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(460, 10, 241, 291))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.AlgoBox = QtGui.QComboBox(self.groupBox_2)
        self.AlgoBox.setGeometry(QtCore.QRect(10, 60, 101, 22))
        self.AlgoBox.setObjectName(_fromUtf8("AlgoBox"))
        self.AlgoBox.addItem(_fromUtf8(""))
        self.AlgoBox.addItem(_fromUtf8(""))
        self.AlgoBox.addItem(_fromUtf8(""))
        self.AlgoBox.addItem(_fromUtf8(""))
        self.AlgoLabel = QtGui.QLabel(self.groupBox_2)
        self.AlgoLabel.setGeometry(QtCore.QRect(40, 30, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AlgoLabel.setFont(font)
        self.AlgoLabel.setObjectName(_fromUtf8("AlgoLabel"))
        self.comboBox = QtGui.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(130, 60, 69, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(140, 30, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.EncryptButton = QtGui.QPushButton(self.groupBox_2)
        self.EncryptButton.setGeometry(QtCore.QRect(10, 140, 75, 23))
        self.EncryptButton.setObjectName(_fromUtf8("EncryptButton"))
        self.DecryptButton = QtGui.QPushButton(self.groupBox_2)
        self.DecryptButton.setGeometry(QtCore.QRect(110, 140, 75, 23))
        self.DecryptButton.setObjectName(_fromUtf8("DecryptButton"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 441, 81))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 371, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.Text_Go_Btn = QtGui.QPushButton(self.groupBox_3)
        self.Text_Go_Btn.setGeometry(QtCore.QRect(310, 50, 75, 23))
        self.Text_Go_Btn.setObjectName(_fromUtf8("Text_Go_Btn"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 80, 441, 71))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 20, 371, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.Sel_File_Btn = QtGui.QPushButton(self.groupBox_4)
        self.Sel_File_Btn.setGeometry(QtCore.QRect(230, 40, 75, 23))
        self.Sel_File_Btn.setObjectName(_fromUtf8("Sel_File_Btn"))
        self.File_Go_Btn = QtGui.QPushButton(self.groupBox_4)
        self.File_Go_Btn.setGeometry(QtCore.QRect(310, 40, 75, 23))
        self.File_Go_Btn.setObjectName(_fromUtf8("File_Go_Btn"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 160, 441, 61))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 20, 371, 20))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.inputBox = QtGui.QGroupBox(self.tab_3)
        self.inputBox.setGeometry(QtCore.QRect(10, 10, 421, 101))
        self.inputBox.setObjectName(_fromUtf8("inputBox"))
        self.lineEdit_4 = QtGui.QLineEdit(self.inputBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 30, 381, 20))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.Check_Parity_BTN = QtGui.QPushButton(self.inputBox)
        self.Check_Parity_BTN.setGeometry(QtCore.QRect(220, 60, 75, 23))
        self.Check_Parity_BTN.setObjectName(_fromUtf8("Check_Parity_BTN"))
        self.COMP_PArity_Btn = QtGui.QPushButton(self.inputBox)
        self.COMP_PArity_Btn.setGeometry(QtCore.QRect(300, 60, 91, 23))
        self.COMP_PArity_Btn.setObjectName(_fromUtf8("COMP_PArity_Btn"))
        self.comboBox_2 = QtGui.QComboBox(self.inputBox)
        self.comboBox_2.setGeometry(QtCore.QRect(110, 60, 91, 22))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 120, 421, 80))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.lineEdit_5 = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 30, 381, 20))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "All in One crypto calculator (beta)", None))
        self.groupBox.setTitle(_translate("Dialog", "Data", None))
        self.DataLabel.setText(_translate("Dialog", "Data", None))
        self.ResultLabel.setText(_translate("Dialog", "Result", None))
        self.KeyLabel.setText(_translate("Dialog", "Key", None))
        self.KCVLabel.setText(_translate("Dialog", "KCV", None))
        self.KCVButton.setText(_translate("Dialog", "Compute KCV only", None))
        self.VectorLabel.setText(_translate("Dialog", "Initial Vector", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Settings", None))
        self.AlgoBox.setItemText(0, _translate("Dialog", "DES", None))
        self.AlgoBox.setItemText(1, _translate("Dialog", "3DES", None))
        self.AlgoBox.setItemText(2, _translate("Dialog", "AES", None))
        self.AlgoBox.setItemText(3, _translate("Dialog", "XOR", None))
        self.AlgoLabel.setText(_translate("Dialog", "Algo", None))
        self.comboBox.setItemText(0, _translate("Dialog", "CBC", None))
        self.comboBox.setItemText(1, _translate("Dialog", "ECB", None))
        self.label.setText(_translate("Dialog", "Mode", None))
        self.EncryptButton.setText(_translate("Dialog", "Encrypt", None))
        self.DecryptButton.setText(_translate("Dialog", "Decrypt", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Encrypt/Decrypt", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Text Input", None))
        self.Text_Go_Btn.setText(_translate("Dialog", "GO!", None))
        self.groupBox_4.setTitle(_translate("Dialog", "File Input", None))
        self.Sel_File_Btn.setText(_translate("Dialog", "Select File", None))
        self.File_Go_Btn.setText(_translate("Dialog", "GO!", None))
        self.groupBox_5.setTitle(_translate("Dialog", "Result (SHA-1)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Hashes", None))
        self.inputBox.setTitle(_translate("Dialog", "Input", None))
        self.Check_Parity_BTN.setText(_translate("Dialog", "Check Parity", None))
        self.COMP_PArity_Btn.setText(_translate("Dialog", "Compute Parity", None))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Odd parity", None))
        self.comboBox_2.setItemText(1, _translate("Dialog", "Even parity", None))
        self.groupBox_7.setTitle(_translate("Dialog", "Result", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Parity", None))

